### ISSUE TITLE
Spam !start

### ISSUE THREAD

**Issue by V3nue** [Myll/DiscordBNetBridge#1]
Heya, first i wanna thank ya for this.
I got it all setup, however as soon as i enable it and type the !start command, it just spams it.

https://i.imgur.com/uo1RgxM.png

any ideas what im doing wrong?

**Comment by V3nue** [comment]
Just a further point, any messages will get spammed. so any other messages sent will spam after !start as well.

**Comment by Myll** [comment]
Hi, sorry I just saw this. Looks like I have Github notifications turned off.

Please verify the following:
In the config.json, for "your_discord_id", this needs to be the ID of the user issuing the !start command (which looks to be the user "Stealthbot" in this case). After !start, the bot should respond like this:

![](https://i.imgur.com/AweKGLx.png)

If the above is true and the issue is still occurring, try the steps again but run DiscordBNetBridge and Stealthbot as administrator.

If nothing here works, I'll have to add some additional logging to help identify the cause.

**Comment by Myll** [comment]
I was able to repro this. Running both as admin fixed the issue (looks like Stealthbot didn't have access to write to msgs_from_discord_done.txt).

**Comment by V3nue** [comment]
tyvm!
